assets: /home/leisongao/LIBERO/libero/libero/./assets
bddl_files: /home/leisongao/LIBERO/libero/libero/./bddl_files
benchmark_root: /home/leisongao/LIBERO/libero/libero
datasets: /home/leisongao/LIBERO/libero/libero/../datasets
init_states: /home/leisongao/LIBERO/libero/libero/./init_files
